### ISSUE TITLE
Perhaps a bit more guidance on install and running?

### ISSUE THREAD

**Issue by tahickson** [natcap/tiling#1]
I have been struggling for about 12 hours to get this code to run on both a mac and a pc. Mainly, I am struggling with getting the dependencies to install (GDAL and pygeoprocessing) at all. I've run pip from python3. I have tried using Docker as suggested. I've tried using Homebrew. My suspicion is that there may be permissions issues on the mac and VM issues on the PC, but it's really quite hard to know. It would be very helpful for us not-entirely-expert users if you could provide a bit more guidance.

**Comment by dcdenu4** [comment]
Hi @tahickson sorry you're having issues getting set up to run this utility. Are you by chance familiar with `conda`? We've internally been using that quite a bit lately to keep consistent environments set up. There's a post on the NatCap forums that gives a decent run down of getting set up: https://community.naturalcapitalproject.org/t/invest-python-package-installation-error-from-source-on-linux-os/1670/6

There's also this source that helps get set up with InVEST, but has a lot of the same requirements.
https://invest.readthedocs.io/en/latest/installing.html

We will add some of these resources in the `readme` for getting a workable environment setup.

For reference this is a created utility for internal use so we didn't expect much traffic. If you don't mind me asking I'd be curious how you came across it? Cheers!

**Comment by tahickson** [comment]
Thanks so much for your reply. I got it to work this morning using conda. Wasn’t exactly straightforward, but now I’m a bad ass…

I’ll take a look at the links you shared and see if they would have helped me. Maybe I can offer back some help based on my experience.

From: Doug ***@***.***>
Reply-To: natcap/wallpaper-scenarios ***@***.***>
Date: Monday, March 15, 2021 at 1:53 PM
To: natcap/wallpaper-scenarios ***@***.***>
Cc: "Hickson, Thomas A." ***@***.***>, Mention ***@***.***>
Subject: [External] Re: [natcap/wallpaper-scenarios] Perhaps a bit more guidance on install and running? (#1)


Hi @tahickson<https://github.com/tahickson> sorry you're having issues getting set up to run this utility. Are you by chance familiar with conda? We've internally been using that quite a bit lately to keep consistent environments set up. There's a post on the NatCap forums that gives a decent run down of getting set up: https://community.naturalcapitalproject.org/t/invest-python-package-installation-error-from-source-on-linux-os/1670/6

There's also this source that helps get set up with InVEST, but has a lot of the same requirements.
https://invest.readthedocs.io/en/latest/installing.html

We will add some of these resources in the readme for getting a workable environment setup.

For reference this is a created utility for internal use so we didn't expect much traffic. If you don't mind me asking I'd be curious how you came across it? Cheers!

**Comment by richpsharp** [comment]
Thanks @dcdenu4 and sorry @tahickson, this was just a one-off project we made in an hour as part of an internal planning meeting we had a few months ago. Never thought someone would find it. For what it is, I hope it's useful!
